import os
import subprocess
import sys
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# --------- CONFIGURATION ----------
YOUR_NAME = "Evans Langat"
CHALLENGES = [
    "Handling pre-existing folders causing FileExistsError",
    "Ensuring correct cloning of repositories every time",
    "Generating both Markdown and PDF outputs automatically",
    "Managing dependencies and Python environment consistency"
]

def run_command(command):
    try:
        result = subprocess.run(command, shell=True, check=True, capture_output=True, text=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"⚠️ Error: {e.stderr}")
        return None

def clone_repository(repo_url, input_path):
    if input_path.exists():
        print("🧹 Removing existing repository folder...")
        subprocess.run(f"rm -rf {input_path}", shell=True)
    print(f"📥 Cloning repository from {repo_url}...")
    result = run_command(f"git clone {repo_url} {input_path}")
    if result is None:
        print("⚠️ Failed to clone repository. Check URL or network connection.")
        sys.exit(1)
    print("✅ Repository cloned successfully!")

def generate_docs(repo_url, input_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    md_file = output_dir / "DOCUMENTATION.md"
    pdf_file = output_dir / "DOCUMENTATION.pdf"

    md_content = f"""# Documentation for {repo_url}

Generated by Codebase Genius

**Author:** {YOUR_NAME}

**Cloned repository:** {input_path}

## Challenges Faced
""" + "".join([f"- {c}\n" for c in CHALLENGES]) + """

## Codebase Diagram

![Diagram Placeholder](diagram_placeholder.png)

*This diagram represents high-level relationships between modules/classes/functions.*
"""

    with open(md_file, "w") as f:
        f.write(md_content)
    print(f"✅ Markdown documentation generated: {md_file}")

    # PDF generation
    c = canvas.Canvas(str(pdf_file), pagesize=A4)
    c.setFont("Helvetica", 12)
    y = 800
    for line in md_content.splitlines():
        c.drawString(50, y, line)
        y -= 20
        if y < 50:
            c.showPage()
            c.setFont("Helvetica", 12)
            y = 800
    c.save()
    print(f"✅ PDF documentation generated: {pdf_file}")

def main():
    base_dir = Path.home() / "codebase_genius"
    repo_url = input("Enter a GitHub repository URL: ").strip()
    if not repo_url.startswith("https://github.com/"):
        print("❌ Invalid URL. Please enter a valid GitHub repository link.")
        sys.exit(1)

    input_path = base_dir / "input_repo"
    repo_name = repo_url.rstrip('/').split('/')[-1]
    output_dir = base_dir / f"output/{repo_name}_doc"

    if output_dir.exists():
        subprocess.run(f"rm -rf {output_dir}", shell=True)

    clone_repository(repo_url, input_path)
    generate_docs(repo_url, input_path, output_dir)

if __name__ == "__main__":
    main()
