import json
import os

ANALYSIS_PATH = "/home/evans/codebase_genius/output/analysis.json"
OUTPUT_DOC = "/home/evans/codebase_genius/output/DOCUMENTATION.md"

def generate_documentation():
    if not os.path.exists(ANALYSIS_PATH):
        print("❌ No analysis data found.")
        return

    with open(ANALYSIS_PATH, "r") as f:
        data = json.load(f)

    files = data.get("files", [])
    total_files = len(files)

    doc_content = [
        "# 🧠 Codebase Genius Documentation\n",
        f"## Repository Overview\nThis repository contains **{total_files}** Python files.\n"
    ]

    if total_files > 0:
        doc_content.append("## File Analysis\n")
        for f_info in files:
            doc_content.append(f"- **{f_info['path']}** — {f_info['lines']} lines\n")

    doc_content.append("\n---\n📘 *Generated by Codebase Genius — AI-powered documentation assistant.*")

    with open(OUTPUT_DOC, "w") as f:
        f.write("\n".join(doc_content))

    print(f"🪄 Documentation generated: {OUTPUT_DOC}")

if __name__ == "__main__":
    generate_documentation()
